### ISSUE TITLE
Can't seem to run train.py 

### ISSUE THREAD

**Issue by Shashi456** [marco-c/autowebcompat#121]
Although i can pretrain.py successfully , i cant seem to run train.py. Except for the initial code the rest of the code seems same . 

``` bash

Traceback (most recent call last):
  File "train.py", line 11, in <module>
    image = utils.load_image(all_images[0])
  File "G:\Code\autowebcompat\autowebcompat\utils.py", line 81, in load_image
    img = load_img(os.path.join(parent_dir, fname), target_size=(32, 24))
  File "C:\Users\pawan sasanka\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\preprocessing\image.py", line 347, in load_img
    img = pil_image.open(path)
  File "C:\Users\pawan sasanka\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2312, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data_resized\\10003'
```

Does anyone have any idea why?

**Comment by Shashi456** [comment]
@marco-c  do you think its a local error?

**Comment by marco-c** [comment]
dba9e1ff6808cb5b2151373c32d2da5b3040f8b9 fixes the problem

**Comment by Shashi456** [comment]
@marco-c  i'm still getting these errors : 
``` bash 
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    data_gen = utils.get_ImageDataGenerator(all_images, input_shape)
  File "G:\Code\autowebcompat\autowebcompat\utils.py", line 94, in get_ImageDataGenerator
    x[i] = load_image(image)
  File "G:\Code\autowebcompat\autowebcompat\utils.py", line 80, in load_image
    img = load_img(os.path.join(parent_dir, fname), target_size=(32, 24))
  File "C:\Users\pawan sasanka\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\preprocessing\image.py", line 347, in load_img
    img = pil_image.open(path)
  File "C:\Users\pawan sasanka\AppData\Local\Programs\Python\Python36\lib\site-packages\PIL\Image.py", line 2312, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'data_resized\\10003'
```

and also this 
Traceback (most recent call last):
  File "train.py", line 38, in <module>
    train_couples_len = sum(1 for e in gen_func(images_train))
  File "train.py", line 38, in <genexpr>
    train_couples_len = sum(1 for e in gen_func(images_train))
  File "train.py", line 31, in couples_generator
    yield load_pair(i), labels[i]
KeyError: '6408_6'

**Comment by marco-c** [comment]
The labels error is expected since we have no labels yet. We should maybe make it work with the labels we have, filtering out the images with no labels, but it's another issue.

**Comment by Shashi456** [comment]
@marco-c  did the No file or directory issue get solved?

**Comment by marco-c** [comment]
Yes, the first issue should be solved now. A PR for the second issue would be welcome, but please file an issue first.

**Comment by Shashi456** [comment]
@marco-c  as a temporary measure would you want to add a try except block to the couple_generator, that way training atleast wouldn't stop ?

**Comment by marco-c** [comment]
> @marco-c as a temporary measure would you want to add a try except block to the couple_generator, that way training atleast wouldn't stop ?

I think it's better to implement the clean solution directly, since it's easy (at the beginning of train.py the images that have no labels should be discarded).

**Comment by marco-c** [comment]
I've filed #138.
