### ISSUE TITLE
Convert string labels to categories

### ISSUE THREAD

**Issue by Shashi456** [marco-c/autowebcompat#142]
The following error comes up when i try to run train.py

``` python 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\pawan sasanka\AppData\Local\Programs\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\pawan sasanka\AppData\Local\Programs\Python\Python36\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\pawan sasanka\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\data_utils.py", line 630, in data_generator_task
    generator_output = next(self._generator)
  File "G:\Code\autowebcompat\autowebcompat\utils.py", line 114, in __next__
    return self.next()
  File "G:\Code\autowebcompat\autowebcompat\utils.py", line 128, in next
    y_batch[i] = label
ValueError: could not convert string to float: 'd'

Traceback (most recent call last):
  File ".\train.py", line 47, in <module>
    model.fit_generator(train_iterator, steps_per_epoch=train_couples_len / BATCH_SIZE, epochs=EPOCHS)
  File "C:\Users\pawan sasanka\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\legacy\interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\pawan sasanka\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\training.py", line 2083, in fit_generator
    generator_output = next(output_generator)
StopIteration
```

**Comment by marco-c** [comment]
The labels should be converted to a format that Keras understands.

**Comment by Shashi456** [comment]
@marco-c 
In the labels.csv file, would that look somewhat like i.e a one hot encoding

``` csv
Image   Y  D  N
16      0  1  0
. 
. 
```

or would it rather be  a value like -1,0,1

**Comment by marco-c** [comment]
This is going to be binary classification, so we can just use 1 and 0.

**Comment by Shashi456** [comment]
@marco-c  so we would probably have to two set of labels ? 
To make #143 possible , we could have the first set of labels Y vs D+N and then the second set of labels represents Y+D vs N

**Comment by marco-c** [comment]
What do you mean by two set of labels?

**Comment by Shashi456** [comment]
@marco-c , I mean two columns in the labels.csv . One column which has y as 1 and n+d as 0 . And the other column which has y+d as 1 and n as 0.

**Comment by marco-c** [comment]
I don't see why that would be necessary. We already have the labels as 'y', 'd' or 'n'. We can just transform them to 1 or 0 according to whether we are resolving Y vs D+N or Y+D vs N.

**Comment by Shashi456** [comment]
@marco-c if i make a function for this , i will have to return the labels in a dictionary format right { webcompatid : 1/0} ?

**Comment by marco-c** [comment]
@Shashi456 what do you mean? Maybe if you open a PR showing what you mean it would be easier to discuss.
