### ISSUE TITLE
Make collect.py support Mac and Windows too

### ISSUE THREAD

**Issue by amit2rockon** [marco-c/autowebcompat#32]
Using TensorFlow backend.
10280
_Traceback (most recent call last):
  File "/Users/amit/Documents/GitHub/autowebcompat/collect.py", line 203, in <module>
    firefox_driver = webdriver.Firefox(firefox_profile=firefox_profile, firefox_binary='tools/nightly/firefox-bin')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/firefox/webdriver.py", line 152, in __init__
    keep_alive=True)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 98, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 188, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/webdriver.py", line 256, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: **Unable to find a matching set of capabilities_**

**Comment by amit2rockon** [comment]
Even I tried different versions of selenium and got 3.3.2 to be better , resolved this issue but created the other issue with compatibility of webdrivers.

**Comment by marco-c** [comment]
The script assumes that the system is Linux (it's using the webdriver binaries for Linux and the browser binaries for Linux). We should fix it to support Mac and Windows too.

In the meantime, you can try to run the script in a Linux VM.

**Comment by marco-c** [comment]
Support for Mac has been added with https://github.com/marco-c/autowebcompat/pull/40.

**Comment by marco-c** [comment]
Support for Windows has been added with #42.
